package calc;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicolas
 */
public class Pantalla extends javax.swing.JFrame {
       int operador;
    calc.Calculador miCalculador = new calc.Calculador();
    Trigonométrica miTrigo = new Trigonométrica();

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     void guardarOperador1() {
        float numero; //inicia la var. numero
        numero = Float.valueOf(espacio.getText()); //guarda en numero el valor de espacio

        miCalculador.operador1 = numero; //objeto.atributo=valor

        espacio.setText("");//espacio queda en blanco
    }
    
    void guardarOperadorTrigo() {
        float numero; //inicia la var. numero
        numero = Float.valueOf(espacio.getText()); //guarda en numero el valor de espacio
        miTrigo.operador1 = numero; //objeto.atributo=valor
    }
    
    private void btnSumaMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        guardarOperador1();
        operador = 0;
        espacio.setText("");
    }                                    

    private void btnRestaMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        guardarOperador1();
        operador = 1;
        espacio.setText("");
    }                                     

    private void btnIgualMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        float numero;
        numero = Float.valueOf(espacio.getText());
        
        miCalculador.operador2 = numero;

        switch (operador) {//condición de operador para evitar escribir tanto
            case 0:
                miCalculador.sumar();
                espacio.setText(" "+String.valueOf(miCalculador.resultado));
                break;
            case 1:
                miCalculador.restar();
                espacio.setText(String.valueOf(" " +miCalculador.resultado));
                break;
            case 2:
                miCalculador.mult();
                espacio.setText(String.valueOf(" " +miCalculador.resultado));
                break;
            case 3:
                if(numero==0){
                    espacio.setText("no se puede hacer");
                }
                else{
                    miCalculador.div();
                    espacio.setText(String.valueOf(" " +miCalculador.resultado));
                }
                break;
            
    }                                     
    }
    private void btnMultMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        guardarOperador1();
        operador = 2;
        espacio.setText("");
    }                                    

    private void btnDivMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        guardarOperador1();
        operador = 3;
        espacio.setText("");
    }                                   

    private void senoMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        guardarOperadorTrigo();
        espacio.setText("");
        miTrigo.seno();
        espacio.setText(String.valueOf(" " +miTrigo.resultado));
        
    }                                 

    private void senoActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void cosenoMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        guardarOperadorTrigo();
        espacio.setText("");
        miTrigo.coseno();
        espacio.setText(String.valueOf(" " +miTrigo.resultado));
        
    }                                   

    private void cosenoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void tangenteMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
          guardarOperadorTrigo();
        espacio.setText("");
        miTrigo.tangente();
        espacio.setText(String.valueOf(" " +miTrigo.resultado));
        
    }                                     

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacio = new javax.swing.JTextField();
        btnMult = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        coseno = new javax.swing.JButton();
        seno = new javax.swing.JButton();
        tangente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMult.setText("x");

        btnDiv.setText("/");

        btnResta.setText("-");

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        coseno.setText("COS");
        coseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosenoActionPerformed(evt);
            }
        });

        seno.setText("SENO");
        seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senoActionPerformed(evt);
            }
        });

        tangente.setText("TAN");
        tangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(espacio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMult)
                                .addGap(18, 18, 18)
                                .addComponent(btnDiv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSuma)
                                .addGap(18, 18, 18)
                                .addComponent(btnResta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIgual))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(coseno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tangente)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(espacio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSuma)
                            .addComponent(btnResta)
                            .addComponent(btnIgual))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMult)
                    .addComponent(btnDiv)
                    .addComponent(seno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coseno)
                    .addComponent(tangente))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualActionPerformed

    private void cosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cosenoActionPerformed

    private void senoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senoActionPerformed

    private void tangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tangenteActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed

    }//GEN-LAST:event_btnSumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton coseno;
    private javax.swing.JTextField espacio;
    private javax.swing.JButton seno;
    private javax.swing.JButton tangente;
    // End of variables declaration//GEN-END:variables
}
